/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <malloc.h>
#include <string.h>
#include <android/log.h>
/* Header for class com_var_lib_keywords_Keywords */

#ifndef _Included_com_var_lib_keywords_Keywords
#define _Included_com_var_lib_keywords_Keywords

#define TAG "ANDROID_KEYWORDS"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO ,TAG,__VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR ,TAG,__VA_ARGS__)
#define BUFF_SIZE 1024

#ifdef __cplusplus
extern "C" {
#endif

/* Read buffer array */
char buff[BUFF_SIZE];
/* Memory keywords file pointer */
char *file;

/* Find the index position of the matching string in the original string */
int findCharsIndex(char *, char *);

/*
 * Class:     com_var_lib_keywords_Keywords
 * Method:    loadDict
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT
void JNICALL Java_com_var_lib_keywords_Keywords_loadDict
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_var_lib_keywords_Keywords
 * Method:    hasKeywords
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_var_lib_keywords_Keywords_hasKeywords
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_var_lib_keywords_Keywords
 * Method:    replaceKeywords
 * Signature: (Ljava/lang/String;C)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_var_lib_keywords_Keywords_replaceKeywords
        (JNIEnv *, jclass, jstring, jchar);

/*
 * Class:     com_var_lib_keywords_Keywords
 * Method:    destroy
 * Signature: (void)void;
 */
JNIEXPORT void JNICALL Java_com_var_lib_keywords_Keywords_destroy
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
